// Realistic-ish product data for the Nepalese market. Prices are NPR.
// `compatibilityData` fields are consumed by the compatibility engine built
// in Phase 3 — kept flat and predictable so that service can stay simple.

const products = [
  // ---------------- CPU ----------------
  {
    name: 'AMD Ryzen 5 7600X',
    brand: 'AMD',
    category: 'cpu',
    price: 42000,
    description: 'A fast, efficient AM5 CPU great for gaming and everyday productivity.',
    stock: 12,
    rating: 4.6,
    isFeatured: true,
    specifications: { socket: 'AM5', cores: 6, threads: 12, baseClock: '4.7GHz', boostClock: '5.3GHz', tdp: 105, integratedGraphics: 'Radeon Graphics' },
    compatibilityData: { socket: 'AM5', tdp: 105 },
  },
  {
    name: 'AMD Ryzen 7 7800X3D',
    brand: 'AMD',
    category: 'cpu',
    price: 68000,
    description: '3D V-Cache flagship, the go-to CPU for high-FPS gaming builds.',
    stock: 8,
    rating: 4.9,
    isFeatured: true,
    specifications: { socket: 'AM5', cores: 8, threads: 16, baseClock: '4.2GHz', boostClock: '5.0GHz', tdp: 120, integratedGraphics: 'Radeon Graphics' },
    compatibilityData: { socket: 'AM5', tdp: 120 },
  },
  {
    name: 'Intel Core i5-13400F',
    brand: 'Intel',
    category: 'cpu',
    price: 32000,
    description: 'Excellent value LGA1700 CPU for budget-to-mid gaming rigs.',
    stock: 15,
    rating: 4.5,
    isFeatured: false,
    specifications: { socket: 'LGA1700', cores: 10, threads: 16, baseClock: '2.5GHz', boostClock: '4.6GHz', tdp: 65, integratedGraphics: 'None' },
    compatibilityData: { socket: 'LGA1700', tdp: 65 },
  },
  {
    name: 'Intel Core i7-13700K',
    brand: 'Intel',
    category: 'cpu',
    price: 62000,
    description: 'High core-count LGA1700 CPU suited for streaming and rendering.',
    stock: 6,
    rating: 4.7,
    isFeatured: false,
    specifications: { socket: 'LGA1700', cores: 16, threads: 24, baseClock: '3.4GHz', boostClock: '5.4GHz', tdp: 125, integratedGraphics: 'UHD 770' },
    compatibilityData: { socket: 'LGA1700', tdp: 125 },
  },
  {
    name: 'AMD Ryzen 9 7950X',
    brand: 'AMD',
    category: 'cpu',
    price: 95000,
    description: 'Enthusiast-tier 16-core CPU for 3D rendering, AI/ML and heavy multitasking.',
    stock: 4,
    rating: 4.8,
    isFeatured: false,
    specifications: { socket: 'AM5', cores: 16, threads: 32, baseClock: '4.5GHz', boostClock: '5.7GHz', tdp: 170, integratedGraphics: 'Radeon Graphics' },
    compatibilityData: { socket: 'AM5', tdp: 170 },
  },

  // ---------------- GPU ----------------
  {
    name: 'NVIDIA RTX 4060',
    brand: 'NVIDIA',
    category: 'gpu',
    price: 48000,
    description: 'Efficient 1080p gaming GPU with DLSS 3 support.',
    stock: 10,
    rating: 4.4,
    isFeatured: true,
    specifications: { vram: '8GB', memoryType: 'GDDR6', length: 200, tdp: 115, recommendedPSU: 450 },
    compatibilityData: { length: 200, tdp: 115, recommendedPSU: 450 },
  },
  {
    name: 'NVIDIA RTX 4070 Super',
    brand: 'NVIDIA',
    category: 'gpu',
    price: 92000,
    description: 'Strong 1440p performer, a favorite in balanced-to-high builds.',
    stock: 7,
    rating: 4.7,
    isFeatured: true,
    specifications: { vram: '12GB', memoryType: 'GDDR6X', length: 267, tdp: 220, recommendedPSU: 650 },
    compatibilityData: { length: 267, tdp: 220, recommendedPSU: 650 },
  },
  {
    name: 'AMD Radeon RX 7800 XT',
    brand: 'AMD',
    category: 'gpu',
    price: 85000,
    description: 'Great value 1440p GPU with plenty of VRAM.',
    stock: 6,
    rating: 4.6,
    isFeatured: false,
    specifications: { vram: '16GB', memoryType: 'GDDR6', length: 287, tdp: 263, recommendedPSU: 700 },
    compatibilityData: { length: 287, tdp: 263, recommendedPSU: 700 },
  },
  {
    name: 'NVIDIA RTX 4080 Super',
    brand: 'NVIDIA',
    category: 'gpu',
    price: 175000,
    description: 'Enthusiast 4K-ready GPU for high-performance and streaming rigs.',
    stock: 3,
    rating: 4.9,
    isFeatured: true,
    specifications: { vram: '16GB', memoryType: 'GDDR6X', length: 310, tdp: 320, recommendedPSU: 850 },
    compatibilityData: { length: 310, tdp: 320, recommendedPSU: 850 },
  },
  {
    name: 'NVIDIA RTX 4090',
    brand: 'NVIDIA',
    category: 'gpu',
    price: 280000,
    description: 'The absolute flagship for 4K gaming, rendering and AI workloads.',
    stock: 2,
    rating: 5,
    isFeatured: false,
    specifications: { vram: '24GB', memoryType: 'GDDR6X', length: 336, tdp: 450, recommendedPSU: 1000 },
    compatibilityData: { length: 336, tdp: 450, recommendedPSU: 1000 },
  },

  // ---------------- Motherboard ----------------
  {
    name: 'ASUS TUF Gaming B650-Plus',
    brand: 'ASUS',
    category: 'motherboard',
    price: 32000,
    description: 'Reliable AM5 ATX board with solid VRMs for Ryzen 7000-series builds.',
    stock: 9,
    rating: 4.5,
    isFeatured: true,
    specifications: { socket: 'AM5', chipset: 'B650', formFactor: 'ATX', ramType: 'DDR5', ramSlots: 4, maxRam: 128, m2Slots: 2, sataPorts: 4 },
    compatibilityData: { socket: 'AM5', formFactor: 'ATX', ramType: 'DDR5', ramSlots: 4, maxRam: 128 },
  },
  {
    name: 'MSI PRO B760M-A',
    brand: 'MSI',
    category: 'motherboard',
    price: 21000,
    description: 'Budget-friendly LGA1700 Micro-ATX board for Intel 12th/13th gen.',
    stock: 11,
    rating: 4.3,
    isFeatured: false,
    specifications: { socket: 'LGA1700', chipset: 'B760', formFactor: 'Micro-ATX', ramType: 'DDR4', ramSlots: 4, maxRam: 128, m2Slots: 2, sataPorts: 4 },
    compatibilityData: { socket: 'LGA1700', formFactor: 'Micro-ATX', ramType: 'DDR4', ramSlots: 4, maxRam: 128 },
  },
  {
    name: 'Gigabyte X670 AORUS Elite',
    brand: 'Gigabyte',
    category: 'motherboard',
    price: 48000,
    description: 'High-end AM5 ATX board with PCIe 5.0 support for enthusiast builds.',
    stock: 5,
    rating: 4.6,
    isFeatured: false,
    specifications: { socket: 'AM5', chipset: 'X670', formFactor: 'ATX', ramType: 'DDR5', ramSlots: 4, maxRam: 128, m2Slots: 3, sataPorts: 4 },
    compatibilityData: { socket: 'AM5', formFactor: 'ATX', ramType: 'DDR5', ramSlots: 4, maxRam: 128 },
  },
  {
    name: 'ASUS ROG Strix Z790-E',
    brand: 'ASUS',
    category: 'motherboard',
    price: 62000,
    description: 'Premium LGA1700 ATX board built for i7/i9 overclocking.',
    stock: 4,
    rating: 4.7,
    isFeatured: false,
    specifications: { socket: 'LGA1700', chipset: 'Z790', formFactor: 'ATX', ramType: 'DDR5', ramSlots: 4, maxRam: 128, m2Slots: 4, sataPorts: 6 },
    compatibilityData: { socket: 'LGA1700', formFactor: 'ATX', ramType: 'DDR5', ramSlots: 4, maxRam: 128 },
  },
  {
    name: 'MSI MAG B650I Edge',
    brand: 'MSI',
    category: 'motherboard',
    price: 38000,
    description: 'Compact Mini-ITX AM5 board for small-form-factor builds.',
    stock: 6,
    rating: 4.4,
    isFeatured: false,
    specifications: { socket: 'AM5', chipset: 'B650', formFactor: 'Mini-ITX', ramType: 'DDR5', ramSlots: 2, maxRam: 64, m2Slots: 2, sataPorts: 2 },
    compatibilityData: { socket: 'AM5', formFactor: 'Mini-ITX', ramType: 'DDR5', ramSlots: 2, maxRam: 64 },
  },

  // ---------------- RAM ----------------
  {
    name: 'Corsair Vengeance 16GB DDR4',
    brand: 'Corsair',
    category: 'ram',
    price: 6500,
    description: 'Dependable DDR4 kit for budget and mid-range Intel/AMD builds.',
    stock: 20,
    rating: 4.5,
    isFeatured: false,
    specifications: { capacity: '16GB (2x8GB)', type: 'DDR4', speed: '3200MHz', modules: 2 },
    compatibilityData: { type: 'DDR4', capacity: 16 },
  },
  {
    name: 'Corsair Vengeance 32GB DDR5',
    brand: 'Corsair',
    category: 'ram',
    price: 15500,
    description: 'High-speed DDR5 kit, a great match for Ryzen 7000 / Intel 13th gen.',
    stock: 14,
    rating: 4.7,
    isFeatured: true,
    specifications: { capacity: '32GB (2x16GB)', type: 'DDR5', speed: '6000MHz', modules: 2 },
    compatibilityData: { type: 'DDR5', capacity: 32 },
  },
  {
    name: 'G.Skill Trident Z5 32GB DDR5',
    brand: 'G.Skill',
    category: 'ram',
    price: 17800,
    description: 'RGB DDR5 kit tuned for high-performance and enthusiast builds.',
    stock: 9,
    rating: 4.6,
    isFeatured: false,
    specifications: { capacity: '32GB (2x16GB)', type: 'DDR5', speed: '6400MHz', modules: 2 },
    compatibilityData: { type: 'DDR5', capacity: 32 },
  },
  {
    name: 'Kingston Fury Beast 16GB DDR5',
    brand: 'Kingston',
    category: 'ram',
    price: 8200,
    description: 'Affordable single-stick DDR5 upgrade path for newer boards.',
    stock: 18,
    rating: 4.3,
    isFeatured: false,
    specifications: { capacity: '16GB (1x16GB)', type: 'DDR5', speed: '5600MHz', modules: 1 },
    compatibilityData: { type: 'DDR5', capacity: 16 },
  },
  {
    name: 'Corsair Dominator Platinum 64GB DDR5',
    brand: 'Corsair',
    category: 'ram',
    price: 34000,
    description: 'High-capacity DDR5 kit for 3D rendering, AI/ML and heavy workstation use.',
    stock: 5,
    rating: 4.8,
    isFeatured: false,
    specifications: { capacity: '64GB (2x32GB)', type: 'DDR5', speed: '6000MHz', modules: 2 },
    compatibilityData: { type: 'DDR5', capacity: 64 },
  },

  // ---------------- Storage ----------------
  {
    name: 'WD Blue 1TB SATA SSD',
    brand: 'Western Digital',
    category: 'storage',
    price: 7200,
    description: 'Reliable SATA SSD for a fast, affordable OS/games drive.',
    stock: 25,
    rating: 4.4,
    isFeatured: false,
    specifications: { type: 'SSD', capacity: '1TB', interface: 'SATA III', readSpeed: '560MB/s', writeSpeed: '530MB/s' },
    compatibilityData: { interface: 'SATA' },
  },
  {
    name: 'Samsung 980 Pro 1TB NVMe',
    brand: 'Samsung',
    category: 'storage',
    price: 12500,
    description: 'Blazing-fast PCIe 4.0 NVMe SSD, ideal as a primary boot drive.',
    stock: 16,
    rating: 4.8,
    isFeatured: true,
    specifications: { type: 'NVMe SSD', capacity: '1TB', interface: 'PCIe 4.0 x4', readSpeed: '7000MB/s', writeSpeed: '5000MB/s' },
    compatibilityData: { interface: 'M.2 NVMe' },
  },
  {
    name: 'Samsung 990 Pro 2TB NVMe',
    brand: 'Samsung',
    category: 'storage',
    price: 24000,
    description: 'High-capacity, high-speed NVMe SSD for large game libraries and content creation.',
    stock: 10,
    rating: 4.9,
    isFeatured: false,
    specifications: { type: 'NVMe SSD', capacity: '2TB', interface: 'PCIe 4.0 x4', readSpeed: '7450MB/s', writeSpeed: '6900MB/s' },
    compatibilityData: { interface: 'M.2 NVMe' },
  },
  {
    name: 'Seagate Barracuda 2TB HDD',
    brand: 'Seagate',
    category: 'storage',
    price: 6800,
    description: 'Budget mass storage for media, backups, and archives.',
    stock: 20,
    rating: 4.1,
    isFeatured: false,
    specifications: { type: 'HDD', capacity: '2TB', interface: 'SATA III', readSpeed: '190MB/s', writeSpeed: '190MB/s' },
    compatibilityData: { interface: 'SATA' },
  },
  {
    name: 'Crucial P3 500GB NVMe',
    brand: 'Crucial',
    category: 'storage',
    price: 4500,
    description: 'Entry-level NVMe drive, a solid budget boot-drive option.',
    stock: 22,
    rating: 4.2,
    isFeatured: false,
    specifications: { type: 'NVMe SSD', capacity: '500GB', interface: 'PCIe 3.0 x4', readSpeed: '3500MB/s', writeSpeed: '1900MB/s' },
    compatibilityData: { interface: 'M.2 NVMe' },
  },

  // ---------------- PSU ----------------
  {
    name: 'Cooler Master MWE 550W Bronze',
    brand: 'Cooler Master',
    category: 'psu',
    price: 6200,
    description: 'Dependable entry-level PSU for budget and mid-range builds.',
    stock: 18,
    rating: 4.3,
    isFeatured: false,
    specifications: { wattage: 550, efficiency: '80+ Bronze', formFactor: 'ATX', modular: 'Non-Modular' },
    compatibilityData: { wattage: 550, formFactor: 'ATX' },
  },
  {
    name: 'Corsair RM650x 650W Gold',
    brand: 'Corsair',
    category: 'psu',
    price: 11500,
    description: 'Fully modular, quiet, gold-rated PSU — a strong all-rounder.',
    stock: 12,
    rating: 4.8,
    isFeatured: true,
    specifications: { wattage: 650, efficiency: '80+ Gold', formFactor: 'ATX', modular: 'Fully Modular' },
    compatibilityData: { wattage: 650, formFactor: 'ATX' },
  },
  {
    name: 'Seasonic Focus 750W Gold',
    brand: 'Seasonic',
    category: 'psu',
    price: 14200,
    description: 'High-efficiency modular PSU well suited to mid-to-high-end GPUs.',
    stock: 9,
    rating: 4.7,
    isFeatured: false,
    specifications: { wattage: 750, efficiency: '80+ Gold', formFactor: 'ATX', modular: 'Fully Modular' },
    compatibilityData: { wattage: 750, formFactor: 'ATX' },
  },
  {
    name: 'ASUS ROG Strix 850W Gold',
    brand: 'ASUS',
    category: 'psu',
    price: 19500,
    description: 'Premium PSU for enthusiast builds with high-end GPUs.',
    stock: 5,
    rating: 4.8,
    isFeatured: false,
    specifications: { wattage: 850, efficiency: '80+ Gold', formFactor: 'ATX', modular: 'Fully Modular' },
    compatibilityData: { wattage: 850, formFactor: 'ATX' },
  },
  {
    name: 'Corsair HX1000 1000W Platinum',
    brand: 'Corsair',
    category: 'psu',
    price: 32000,
    description: 'Top-tier platinum PSU built for flagship GPUs like the RTX 4090.',
    stock: 3,
    rating: 4.9,
    isFeatured: false,
    specifications: { wattage: 1000, efficiency: '80+ Platinum', formFactor: 'ATX', modular: 'Fully Modular' },
    compatibilityData: { wattage: 1000, formFactor: 'ATX' },
  },

  // ---------------- Case ----------------
  {
    name: 'NZXT H510',
    brand: 'NZXT',
    category: 'case',
    price: 9500,
    description: 'Clean, minimalist ATX case with good cable management.',
    stock: 14,
    rating: 4.5,
    isFeatured: false,
    specifications: { formFactor: 'Mid Tower', supportedMotherboardSizes: ['ATX', 'Micro-ATX', 'Mini-ITX'], gpuMaxLength: 325, cpuCoolerMaxHeight: 165, psuFormFactor: 'ATX' },
    compatibilityData: { supportedMotherboardSizes: ['ATX', 'Micro-ATX', 'Mini-ITX'], gpuMaxLength: 325, cpuCoolerMaxHeight: 165 },
  },
  {
    name: 'Lian Li Lancool 216',
    brand: 'Lian Li',
    category: 'case',
    price: 12500,
    description: 'High-airflow ATX case, popular for high-performance gaming builds.',
    stock: 10,
    rating: 4.8,
    isFeatured: true,
    specifications: { formFactor: 'Mid Tower', supportedMotherboardSizes: ['ATX', 'Micro-ATX', 'Mini-ITX'], gpuMaxLength: 392, cpuCoolerMaxHeight: 181, psuFormFactor: 'ATX' },
    compatibilityData: { supportedMotherboardSizes: ['ATX', 'Micro-ATX', 'Mini-ITX'], gpuMaxLength: 392, cpuCoolerMaxHeight: 181 },
  },
  {
    name: 'Cooler Master NR200',
    brand: 'Cooler Master',
    category: 'case',
    price: 11000,
    description: 'Compact Mini-ITX case for small-form-factor builds.',
    stock: 8,
    rating: 4.5,
    isFeatured: false,
    specifications: { formFactor: 'Mini Tower', supportedMotherboardSizes: ['Mini-ITX'], gpuMaxLength: 330, cpuCoolerMaxHeight: 155, psuFormFactor: 'SFX' },
    compatibilityData: { supportedMotherboardSizes: ['Mini-ITX'], gpuMaxLength: 330, cpuCoolerMaxHeight: 155 },
  },
  {
    name: 'Fractal Design North',
    brand: 'Fractal Design',
    category: 'case',
    price: 15500,
    description: 'Stylish wood-accented ATX case with strong airflow.',
    stock: 7,
    rating: 4.7,
    isFeatured: false,
    specifications: { formFactor: 'Mid Tower', supportedMotherboardSizes: ['ATX', 'Micro-ATX', 'Mini-ITX'], gpuMaxLength: 355, cpuCoolerMaxHeight: 170, psuFormFactor: 'ATX' },
    compatibilityData: { supportedMotherboardSizes: ['ATX', 'Micro-ATX', 'Mini-ITX'], gpuMaxLength: 355, cpuCoolerMaxHeight: 170 },
  },
  {
    name: 'Corsair 5000D Airflow',
    brand: 'Corsair',
    category: 'case',
    price: 17500,
    description: 'Full tower case with excellent airflow and room for large builds.',
    stock: 6,
    rating: 4.8,
    isFeatured: false,
    specifications: { formFactor: 'Full Tower', supportedMotherboardSizes: ['E-ATX', 'ATX', 'Micro-ATX', 'Mini-ITX'], gpuMaxLength: 420, cpuCoolerMaxHeight: 170, psuFormFactor: 'ATX' },
    compatibilityData: { supportedMotherboardSizes: ['E-ATX', 'ATX', 'Micro-ATX', 'Mini-ITX'], gpuMaxLength: 420, cpuCoolerMaxHeight: 170 },
  },

  // ---------------- CPU Cooler ----------------
  {
    name: 'Cooler Master Hyper 212',
    brand: 'Cooler Master',
    category: 'cpu-cooler',
    price: 4200,
    description: 'The classic budget air cooler, reliable for most mid-range CPUs.',
    stock: 20,
    rating: 4.4,
    isFeatured: false,
    specifications: { coolerType: 'Air', supportedSockets: ['AM5', 'AM4', 'LGA1700', 'LGA1200'], height: 159, tdpRating: 150 },
    compatibilityData: { supportedSockets: ['AM5', 'AM4', 'LGA1700', 'LGA1200'], height: 159, tdpRating: 150 },
  },
  {
    name: 'Noctua NH-D15',
    brand: 'Noctua',
    category: 'cpu-cooler',
    price: 13500,
    description: 'Best-in-class dual-tower air cooler for high-TDP CPUs.',
    stock: 9,
    rating: 4.9,
    isFeatured: true,
    specifications: { coolerType: 'Air', supportedSockets: ['AM5', 'AM4', 'LGA1700'], height: 165, tdpRating: 220 },
    compatibilityData: { supportedSockets: ['AM5', 'AM4', 'LGA1700'], height: 165, tdpRating: 220 },
  },
  {
    name: 'Corsair iCUE H100i 240mm AIO',
    brand: 'Corsair',
    category: 'cpu-cooler',
    price: 14500,
    description: '240mm liquid cooler with RGB, great for high-performance builds.',
    stock: 10,
    rating: 4.7,
    isFeatured: false,
    specifications: { coolerType: 'Liquid (AIO 240mm)', supportedSockets: ['AM5', 'AM4', 'LGA1700'], height: 27, tdpRating: 250 },
    compatibilityData: { supportedSockets: ['AM5', 'AM4', 'LGA1700'], height: 27, tdpRating: 250 },
  },
  {
    name: 'NZXT Kraken X63 280mm AIO',
    brand: 'NZXT',
    category: 'cpu-cooler',
    price: 18500,
    description: '280mm AIO for enthusiast builds needing strong sustained cooling.',
    stock: 6,
    rating: 4.6,
    isFeatured: false,
    specifications: { coolerType: 'Liquid (AIO 280mm)', supportedSockets: ['AM5', 'AM4', 'LGA1700'], height: 30, tdpRating: 300 },
    compatibilityData: { supportedSockets: ['AM5', 'AM4', 'LGA1700'], height: 30, tdpRating: 300 },
  },
  {
    name: 'be quiet! Pure Rock 2',
    brand: 'be quiet!',
    category: 'cpu-cooler',
    price: 5200,
    description: 'Quiet, compact air cooler ideal for budget builds.',
    stock: 15,
    rating: 4.3,
    isFeatured: false,
    specifications: { coolerType: 'Air', supportedSockets: ['AM5', 'AM4', 'LGA1700', 'LGA1200'], height: 155, tdpRating: 150 },
    compatibilityData: { supportedSockets: ['AM5', 'AM4', 'LGA1700', 'LGA1200'], height: 155, tdpRating: 150 },
  },
];

module.exports = products;
